### ISSUE TITLE
Identifying Basic Code 

### ISSUE THREAD

**Issue by kevinford** [mallek/vscode-pick-basic-syntax-highlighter#4]
in package.json I updated the following line to identify programs that are saved as .b as basic programs

            "extensions": [".txt", ".pick", ".b", ""],

In pick.configuration.json I added the BEGIN CASE line below to help with auto completes.

    "autoClosingPairs": [
        ["{", "}"],
        ["<", ">"],
        ["[", "]"],
        ["(", ")"],
        ["\"", "\""],
        ["'", "'"],
        ["BEGIN CASE", " CASE END CASE"]
    ],

When you new release came out i had to make the changes again.  is it possible to get these added and maybe for to the official release or what is the process for changes to be made then approved into one of your releases.

Thanks

**Comment by itsxallwater** [comment]
Hey @kevinford! I don't see an issue with those modifications. What you can do is fork the repo here on GitHub, commit your changes to it, and submit a pull request on this repo pointing back to your forked repo.

Alternatively, I've been meaning to get under the hood and make a few other changes and I'd be happy to include these--it just may be a little bit before I get to it.

The only real caveat, of course, is that this repo is maintained by @mallek so ultimately it's up to him what gets merged into master and published.

**Comment by mallek** [comment]
@kevinford. I’ll take a look at this tonight. I see a pull request was submitted.

**Comment by kevinford** [comment]
not sure i did the pull request correctly, so closed it.

**Comment by kevinford** [comment]
Created a new pull request, there are several other lines that could be added like the BEGIN CASE, but was not sure i was doing them correctly so stop with that one.  Would be nice if there was a way to do a carriage return after each CASE and END CASE.  Let me know if there is a different method.

**Comment by itsxallwater** [comment]
I think that's where we'd want to explore IntelliSense functionality being added into the extension. VS Code supports it, it just needs to be defined, but ideally that's where you'd get a suggestion of "CASE" being your next line after you entered "BEGIN CASE". I think the way you're doing it for now works and is not too dissimilar from how I added support for regions in 1.1.1. There is a more formal way for supporting code folding, but it also requires diving into the world of creating these extensions a bit further.
