### ISSUE TITLE
How to open a 

### ISSUE THREAD

**Issue by mdsi2000** [mallek/vscode-pick-basic-syntax-highlighter#7]
Hello!
I just downloaded Visual Studio Code and added the PickBasic extension How do I get to open a MV (Pick) program for editing? Will the program compile within the the VSC screen? I'm not sure where to go from the blank screen. tia

TIA
-Peter G

**Comment by itsxallwater** [comment]
Hi @mdsi2000 and welcome!

Currently, neither VS Code nor this extension will connect to your Pick system such that you can open up an existing Pick program. Essentially, your development via VS Code would be "remote" and you'd need to have a copy of the programs available separate from your Pick server. Some users handle this manually by copying/pasting or executing file transfers to sync the remote code to the Pick server; others use Git as a system of record for code, and deploy from there to Pick via web hooks.

I will say the timing of your request is noteworthy, and if you have any plans on attending the [International Spectrum](https://www.intl-spectrum.com/) conference in Phoenix next month one of my colleagues here at Zumasys will be speaking on this very topic. If you won't be in attendance, certainly we'll have more information forthcoming!

**Comment by mdsi2000** [comment]
Mike thank you for the quick response. I was checking VS to see if it had additional features that Accuterm’s WED didn’t have. I have been using WED since it came out and totally enjoy the features including adding @vm @svm to modify data. 

-Peter G
